/* eslint-disable prettier/prettier */
export const GET_MAIN_DATA = 'GET_MAIN_DATA';

export const GET_SURVEY_DATA = 'GET_SURVEY_DATA';
export const SEND_SURVEY_DATA = 'SEND_SURVEY_DATA';

export const LABEL_GET_INFO = 'LABEL_GET_INFO';
export const LABEL_GET_LEAGUES = 'LABEL_GET_LEAGUES';
export const LABEL_GET_TEAM_NAMES = 'LABEL_GET_TEAM_NAMES';

export const GET_MAIN_GAME_LIST = 'GET_MAIN_GAME_LIST';
export const GET_SRS_GAME_LIST = 'GET_SRS_GAME_LIST';
export const GET_SPECIAL_GAME_LIST = 'GET_SPECIAL_GAME_LIST';

export const GET_LIVE_GAME_LIST = 'GET_LIVE_GAME_LIST';
export const GET_LIVE_GAME_DETAIL_SUBSCRIBED = 'GET_LIVE_GAME_DETAIL_SUBSCRIBED';
export const GET_LIVE_GAME_DETAIL = 'GET_LIVE_GAME_DETAIL';

export const GET_LIVE_SCHEDULE = 'GET_LIVE_SCHEDULE';

export const WS_BETTING_CONNECTED = 'WS_BETTING_CONNECTED';
export const WS_BETTING_SPORTS_STATUS = 'WS_BETTING_SPORTS_STATUS';

export const GAME_CENTER_BETTING_GET_HISTORIES = 'GAME_CENTER_BETTING_GET_HISTORIES';
export const GAME_CENTER_BETTING_GET_HISTORY_DETAIL = 'GAME_CENTER_BETTING_GET_HISTORY_DETAIL';

export const GAME_CENTER_BETTING_GET_CASUAL_HISTORIES = 'GAME_CENTER_BETTING_GET_CASUAL_HISTORIES';

export const MY_PAGE_BETTING_GET_HISTORIES = 'MY_PAGE_BETTING_GET_HISTORIES';
export const MY_PAGE_BETTING_GET_HISTORY_DETAIL = 'MY_PAGE_BETTING_GET_HISTORY_DETAIL';

export const MODAL_BETTING_GET_HISTORIES = 'MODAL_BETTING_GET_HISTORIES';
export const MODAL_BETTING_GET_CASUAL_HISTORIES = 'MODAL_BETTING_GET_CASUAL_HISTORIES';
export const MODAL_BETTING_GET_HISTORY_DETAIL = 'MODAL_BETTING_GET_HISTORY_DETAIL';

export const CART_ADD_BETTING_GAME = 'ADD_BETTING_GAME';
export const CART_REMOVE_BETTING_GAME = 'REMOVE_BETTING_GAME';
export const CART_REMOVE_ALL_GAMES = 'REMOVE_ALL_GAMES';
export const CART_REQ_BETTING_GAMES = 'REQ_BETTING_GAMES';

export const CART_UPDATE_BETTING_ITEM = 'CART_UPDATE_BETTING_ITEM';

export const GET_CANCELABLE_CART_ITEMS = 'GET_CANCELABLE_CART_ITEMS';
export const FETCH_CANCELABLE_CART_ITEMS = 'FETCH_CANCELABLE_CART_ITEMS';

export const ADD_BETTING_ITEM = 'ADD_BETTING_ITEM';
export const REMOVE_BETTING_ITEM = 'REMOVE_BETTING_ITEM';

export const WS_CHATTING_CONNECTED = 'WS_CHATTING_CONNECTED';
export const WS_CHATTING_UPDATE = 'WS_CHATTING_UPDATE';
export const WS_CHATTING_RECEIVE_MESSAGE = 'WS_CHATTING_RECEIVE_MESSAGE';
export const WS_CHATTING_ENTER_USER = 'WS_CHATTING_ENTER_USER';
export const WS_CHATTING_PROCESS = 'WS_CHATTING_PROCESS';

export const CHATTING_GET_HISTORIES = 'CHATTING_GET_HISTORIES';

export const WS_REQ_ONE_ON_ONE_CHAT = 'WS_REQ_ONE_ON_ONE_CHAT';
export const WS_ACCEPT_ONE_ON_ONE_CHAT = 'WS_ACCEPT_ONE_ON_ONE_CHAT';
export const WS_REJECT_ONE_ON_ONE_CHAT = 'WS_REJECT_ONE_ON_ONE_CHAT';

export const CANCEL_BETTING_FOLDER = 'CANCEL_BETTING_FOLDER';

export const CASUAL_APPLY_TOKEN = 'CASUAL_APPLY_TOKEN';

export const GET_GAME_RESULTS = 'GET_GAME_RESULTS';

export const COMMUNITY_GET_HOME_BOARDS = 'COMMUNITY_GET_HOME_BOARDS';
export const NEWS_GET_HOME_BOARDS = 'NEWS_GET_HOME_BOARDS';

export const TRADES_SELL_GET_LIST = 'TRADES_SELL_GET_LIST';
export const TRADES_SELL_GET_LIST_DETAIL = 'TRADES_SELL_GET_LIST_DETAIL';

export const COMMUNITY_GET_BOARDS = 'COMMUNITY_GET_BOARDS';
export const COMMUNITY_GET_BOARD = 'COMMUNITY_GET_BOARD';
export const COMMUNITY_BOARD_WRITE = 'COMMUNITY_BOARD_WRITE';
export const COMMUNITY_BOARD_UPDATE = 'COMMUNITY_BOARD_UPDATE';
export const COMMUNITY_BOARD_DELETE = 'COMMUNITY_BOARD_DELETE';
export const COMMUNITY_GET_HISTORIES = 'COMMUNITY_GET_HISTORIES';

export const COMMUNITY_FILE_UPLOAD = 'COMMUNITY_FILE_UPLOAD';

export const COMMUNITY_BOARD_GET_COMMENTS = 'COMMUNITY_BOARD_GET_COMMENTS';
export const COMMUNITY_BOARD_COMMENT_WRITE = 'COMMUNITY_BOARD_COMMENT_WRITE';
export const COMMUNITY_BOARD_COMMENT_UPDATE = 'COMMUNITY_BOARD_COMMENT_UPDATE';
export const COMMUNITY_BOARD_COMMENT_DELETE = 'COMMUNITY_BOARD_COMMENT_DELETE';

export const STORE_GET_BOARDS = 'STORE_GET_BOARDS';
export const STORE_GET_BOARD = 'STORE_GET_BOARD';
export const STORE_BUY_ITEM = 'STORE_BUY_ITEM';

export const NEWS_GET_BOARDS = 'NEWS_GET_BOARDS';
export const NEWS_GET_BOARD = 'NEWS_GET_BOARD';

export const NOTICE_GET_BOARDS = 'NOTICE_GET_BOARDS';
export const NOTICE_GET_BOARD = 'NOTICE_GET_BOARD';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const PMANG_LOGIN_CHECK = 'PMANG_LOGIN_CHECK';
export const PMANG_USER_REGISTER = 'PMANG_USER_REGISTER';
export const CHECK_DUPLICATE_NICKNAME = 'CHECK_DUPLICATE_NICKNAME';

export const GET_USER_POLICIES = 'GET_USER_POLICIES';

export const PMANG_USER_UNREGISTER = 'PMANG_USER_UNREGISTER';

export const USER_GET_MESSAGES = 'USER_GET_MESSAGES';
export const USER_WRITE_MESSAGES = 'USER_WRITE_MESSAGES';
export const USER_WRITE_RANDOM_MESSAGES = 'USER_WRITE_RANDOM_MESSAGES';

export const USER_SAFEBOX_LOAD = 'USER_SAFEBOX_LOAD';
export const USER_SAFEBOX_UPDATE = 'USER_SAFEBOX_UPDATE';

export const USER_TOGGLE_OPTIONS = 'USER_TOGGLE_OPTIONS';
export const USER_GET_NICKNAME = 'USER_GET_NICKNAME';

export const MYPAGE_GET_FAQ = 'MYPAGE_GET_FAQ';
export const MYPAGE_GET_INVENTORY = 'MYPAGE_GET_INVENTORY';
export const MYPAGE_CHANGE_INVENTORY = 'MYPAGE_CHANGE_INVENTORY';

export const MYPAGE_GET_HISTORY = 'MYPAGE_GET_HISTORY';

export const MY_PAGE_GET_MY_QUESTIONS = 'MY_PAGE_GET_MY_QUESTIONS';
export const MY_PAGE_GET_MY_QUESTION = 'MY_PAGE_GET_MY_QUESTION';
export const MY_PAGE_WRITE_MY_QUESTION = 'MY_PAGE_WRITE_MY_QUESTION';
export const MY_PAGE_GET_MY_QUESTION_BETS = 'MY_PAGE_GET_MY_QUESTION_BETS';
export const MY_PAGE_DELETE_MY_QUESTION = 'MY_PAGE_DELETE_MY_QUESTION';
